# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170122_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Content',
            new_name='detail',
        ),
    ]
